version: '3.9'

services:
  web:
    build: .
    container_name: django-app
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=0
      - SECRET_KEY=changeme123
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - DB_NAME=santichaidb
      - DB_USER=admin
      - DB_PASSWORD=securepassword
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: santichaidb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: